export const fallbackSettings = {
  storeName: "Waheed Herbal Store",
  phone: "+92 300 0000000",
  whatsappNumber: "923000000000",
  address: "Karachi, Pakistan",
  shippingText: "Nationwide delivery in 3-5 working days with Cash on Delivery.",
  supportCopy: "Need help choosing a remedy? Our support team can guide you on WhatsApp.",
};

export const fallbackCategories = [
  {
    id: "672000000000000000000001",
    name: "Herbal Medicines",
    slug: "herbal-medicines",
    description: "Trusted Unani and herbal formulas for everyday wellness.",
    _count: { products: 2 },
  },
  {
    id: "672000000000000000000002",
    name: "Organic Herbs",
    slug: "organic-herbs",
    description: "Premium loose herbs, seeds, powders, and natural pantry staples.",
    _count: { products: 2 },
  },
  {
    id: "672000000000000000000003",
    name: "Oils & Honey",
    slug: "oils-honey",
    description: "Cold-pressed oils, pure honey, and traditional household essentials.",
    _count: { products: 2 },
  },
  {
    id: "672000000000000000000004",
    name: "Hair & Skin Care",
    slug: "hair-skin-care",
    description: "Natural care products for hair, skin, and personal care routines.",
    _count: { products: 2 },
  },
];

const images = [
  "linear-gradient(135deg,#f2f7e9,#cde0b8 48%,#708c55)",
  "linear-gradient(135deg,#fbf4df,#e2b66e 50%,#6d4c26)",
  "linear-gradient(135deg,#ecf8f1,#91c7a3 48%,#35664a)",
  "linear-gradient(135deg,#fff6ef,#dd997d 48%,#723c31)",
  "linear-gradient(135deg,#f4f7ff,#aebee6 50%,#405480)",
  "linear-gradient(135deg,#fffbea,#e3cf7c 50%,#80662a)",
];

export const fallbackProducts = [
  {
    id: "672000000000000000000101",
    name: "Karakoram Shilajit Resin 30g",
    slug: "karakoram-shilajit-resin-30g",
    description: "A mineral-rich resin prepared for traditional strength and stamina support.",
    benefits: "Supports vitality, daily energy, and recovery from fatigue.",
    usage: "Take a pea-sized amount in warm milk or water once daily, or as advised by a practitioner.",
    packing: "30g sealed glass jar",
    regularPrice: 6200,
    salePrice: 4500,
    stock: 18,
    images: JSON.stringify([images[0]]),
    featured: true,
    bestSeller: true,
    status: "active",
    categoryId: fallbackCategories[0].id,
    category: fallbackCategories[0],
  },
  {
    id: "672000000000000000000102",
    name: "Moringa Leaf Powder",
    slug: "moringa-leaf-powder",
    description: "Fine-ground moringa leaves for smoothies, warm drinks, and daily nutrition routines.",
    benefits: "A natural source of plant nutrients and antioxidants.",
    usage: "Mix half to one teaspoon with water, juice, or food once daily.",
    packing: "100g resealable pouch",
    regularPrice: 650,
    salePrice: 520,
    stock: 42,
    images: JSON.stringify([images[1]]),
    featured: true,
    bestSeller: true,
    status: "active",
    categoryId: fallbackCategories[1].id,
    category: fallbackCategories[1],
  },
  {
    id: "672000000000000000000103",
    name: "Joshanda Herbal Blend",
    slug: "joshanda-herbal-blend",
    description: "A comforting herbal tea blend for seasonal wellness and warm evening routines.",
    benefits: "Helps soothe the throat and supports respiratory comfort.",
    usage: "Boil one sachet in a cup of water for 3-5 minutes. Drink warm.",
    packing: "45g box",
    regularPrice: 260,
    salePrice: 210,
    stock: 66,
    images: JSON.stringify([images[2]]),
    featured: false,
    bestSeller: true,
    status: "active",
    categoryId: fallbackCategories[0].id,
    category: fallbackCategories[0],
  },
  {
    id: "672000000000000000000104",
    name: "Pure Berri Honey",
    slug: "pure-berri-honey",
    description: "Naturally sweet honey selected for everyday breakfast, drinks, and household use.",
    benefits: "A clean pantry staple with a rich taste and smooth texture.",
    usage: "Use as a natural sweetener or take one spoon daily.",
    packing: "500g jar",
    regularPrice: 1800,
    salePrice: 1490,
    stock: 25,
    images: JSON.stringify([images[3]]),
    featured: true,
    bestSeller: false,
    status: "active",
    categoryId: fallbackCategories[2].id,
    category: fallbackCategories[2],
  },
  {
    id: "672000000000000000000105",
    name: "Adivasi Hair Oil",
    slug: "adivasi-hair-oil",
    description: "A botanical hair oil blend for scalp massage and weekly care rituals.",
    benefits: "Supports scalp nourishment and helps reduce dry, brittle hair feel.",
    usage: "Massage into scalp 2-3 times weekly and wash after 2 hours.",
    packing: "120ml bottle",
    regularPrice: 2350,
    salePrice: 1850,
    stock: 15,
    images: JSON.stringify([images[4]]),
    featured: false,
    bestSeller: true,
    status: "active",
    categoryId: fallbackCategories[3].id,
    category: fallbackCategories[3],
  },
  {
    id: "672000000000000000000106",
    name: "Cold Pressed Mustard Oil",
    slug: "cold-pressed-mustard-oil",
    description: "Aromatic mustard oil prepared for cooking, massage, and traditional household use.",
    benefits: "Rich flavor, warming feel, and versatile everyday utility.",
    usage: "Use as preferred for cooking or external massage.",
    packing: "250ml bottle",
    regularPrice: 720,
    salePrice: null,
    stock: 31,
    images: JSON.stringify([images[5]]),
    featured: true,
    bestSeller: false,
    status: "active",
    categoryId: fallbackCategories[2].id,
    category: fallbackCategories[2],
  },
];

export const fallbackCertificates = [
  {
    id: "672000000000000000000201",
    title: "Product Authenticity Certificate",
    type: "Certificate",
    description: "Quality assurance certificate placeholder for herbal product sourcing.",
    fileUrl: "linear-gradient(135deg,#f8fbf2,#cedbb3)",
    published: true,
  },
  {
    id: "672000000000000000000202",
    title: "Batch Lab Report",
    type: "Lab Report",
    description: "Sample lab report placeholder for purity, packaging, and batch review.",
    fileUrl: "linear-gradient(135deg,#f4f8ff,#b8c8e8)",
    published: true,
  },
  {
    id: "672000000000000000000203",
    title: "Supplier Verification",
    type: "Certificate",
    description: "Supplier verification placeholder for future scanned documentation.",
    fileUrl: "linear-gradient(135deg,#fff8ee,#e1b883)",
    published: true,
  },
];

